settings:
  title: 'PickEasy Status Page'
  url: 'https://status.pickeasy.ca' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: pickeasy # unique identifier
    name: PickEasy Site
    url: 'https://pickeasy.ca/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
  - id: pickeasy-menu # unique identifier
    name: PickEasy Menu App
    url: 'https://menus.pickeasy.ca/restaurants/718DBHX' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: pickeasy-menu-api # unique identifier
    name: PickEasy Menu API
    url: 'https://menus-api.pickeasy.ca/api/v2/restaurants/718DBHX' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
